name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem would this solve? Why do you need it?
      placeholder: |
        When leveling multiple professions, I have to switch characters
        to check what materials my alt already has...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: |
        Add an option to show materials across all characters...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other ways to solve this you've thought about?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or mockups
      description: Visual ideas if applicable
      placeholder: Drag and drop image here
    validations:
      required: false
